---
# tasks file for roles/site-smoke-test
#- name: Collect info
- when: type == 'db'
  become: yes
  become_user: postgres
  block: 
      - name: Collect info
        postgresql_info:
          db: flask_db
          filter:
          - tablespaces

      - name: Create test_table with 3 columns in default tablespace
        postgresql_table:
          db: flask_db
          name: test_table
          columns:
          - id bigserial primary key
          - num bigint
          - stories text


      - name: Insert query to test_table in db flask_db
        postgresql_query:
          db: flask_db
          query: INSERT INTO test_table (num, stories) VALUES (2, 'test info')


      - name: Select query to db flask_db with positional arguments and non-default credentials
        postgresql_query:
          db: flask_db
          query: SELECT * FROM test_table 
