---
# tasks file for roles/site-smoke-test
#- name: Collect info
- when: type == 'db'
  become: yes
  become_user: postgres
  block: 
      - name: Collect info
        postgresql_info:
          db: flask_db
          filter:
          - tablespaces

      - name: Create test_table with 3 columns in default tablespace
        postgresql_table:
          db: flask_db
          name: test_table
          columns:
          - id bigserial primary key
          - num bigint
          - stories text


      - name: Insert query to test_table in db flask_db
        postgresql_query:
          db: flask_db
          query: INSERT INTO test_table (num, stories) VALUES (2, 'test info')


      - name: Select query to db flask_db with positional arguments and non-default credentials
        postgresql_query:
          db: flask_db
          query: SELECT * FROM test_table 


- when: type == 'lb'
  block: 
      - name: Test Website availabilty via frontend
        uri:
#          url: "http://{{ frontends.public_v4 }}"
          url: "http://{{ hostvars.item.host_name }}"
          status_code: 200
          return_content: yes
#        when: 'item.hostname == "frontend"'
        loop: "{{ groups.frontends }}"
        delegate_to: workstation
        register: qa_webpage
        ignore_errors: yes


      - name: Fail if 'Ansible has done its job' is not in the page content
        fail:
        when: "'Ansible has done its job' not in qa_webpage.results[0].content"
        tags:
          - osp.smoke
