---
# tasks file for roles/osp-instance-delete
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
     register: result

   - name: Delete instances
     os_server:
        cloud: openstack
        name: "{{ __osp.name }}"
        state: absent
     loop: "{{ result.openstack_servers }}"
     loop_control:
       loop_var: __osp
